// src/App.tsx
import { ControlPanel } from './components/ControlPanel'
import { SheetView } from './components/SheetView'
import { useStore } from './state/store'

export function App() {
  const { state } = useStore()

  return (
    <div className="app">
      <ControlPanel />
      <main className="sheets">
        {state.boegen.length === 0 ? (
          <p className="empty">Keine Bögen ausgewählt - links einen Bogen hinzufügen.</p>
        ) : (
          state.boegen.map((b) => <SheetView key={b.id} bogen={b} />)
        )}
      </main>
    </div>
  )
}

// src/App.vue
<script setup lang="ts">
import { useStore } from './state/store'
import ControlPanel from './components/ControlPanel.vue'
import SheetView from './components/SheetView.vue'

const { state } = useStore()
</script>

<template>
  <div class="app">
    <ControlPanel />
    <main class="sheets">
      <p v-if="state.boegen.length === 0" class="empty">
        Keine Bögen ausgewählt - links einen Bogen hinzufügen.
      </p>
      <template v-else>
        <SheetView v-for="b in state.boegen" :key="b.id" :bogen="b" />
      </template>
    </main>
  </div>
</template>
